const Constants = {
  GET_ALL_SCOOTERS_SUCCESS: 'GET_ALL_SCOOTERS_SUCCESS',
  GET_ALL_SCOOTERS_FAILURE: 'GET_ALL_SCOOTERS_FAILURE',
  ADD_NEW_SCOOTER_SUCCESS: 'ADD_NEW_SCOOTER_SUCCESS',
  ADD_NEW_SCOOTER_FAILURE: 'ADD_NEW_SCOOTER_FAILURE',
  DELETE_SCOOTER_SUCCESS: 'DELETE_SCOOTER_SUCCESS',
  DELETE_SCOOTER_FAILURE: 'DELETE_SCOOTER_FAILURE',
  DISPLAY_SCOOTER: 'DISPLAY_SCOOTER',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',
  GET_FAVOURITES_SUCCESS: 'GET_FAVOURITES_SUCCESS',
  GET_FAVOURITES_FAILURE: 'GET_FAVOURITES_FAILURE',
  ADD_FAVOURITE_SUCCESS: 'ADD_FAVOURITE_SUCCESS',
  ADD_FAVOURITE_FAILURE: 'ADD_FAVOURITE_FAILURE',
};

export default Constants;
